using CSV, DataFrames, LaTeXStrings, Plots
import Plots: mm

# MATLAB-style defaults
default(
    framestyle              = :box,
    background_color        = :white,
    background_color_inside = :white,
    foreground_color_border = :black,
    foreground_color_axis   = :black,
    foreground_color_text   = :black,
    foreground_color_guide  = :black,
    tick_direction          = :out,
    grid                    = false,
    minorticks              = false,
    linewidth               = 1.5,
    legend_background_color = :white,
    legend_foreground_color = :black,
)

c1 = "#1B263B"
c2 = "#FF6B6B"
c3 = "#D4A017"
c4 = "#06D6A0"
c5 = "#3399FF"
c6 = "#FF66CC"
c7 = "#CCFF66"
c8 = "#FF3300"

sp = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\second-iteration-of-sims\\DMPC\\set-point-mpc-probs-n3000.csv", DataFrame)[2709:2714, :]
traj_2709_1 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2709-dmpc-1.csv", DataFrame)
traj_2709_2 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2709-dmpc-2.csv", DataFrame)
traj_2709_3 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2709-dmpc-3.csv", DataFrame)
traj_2709_4 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2709-dmpc-4.csv", DataFrame)
traj_2709_5 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2709-dmpc-5.csv", DataFrame)
traj_2709_6 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2709-dmpc-6.csv", DataFrame)
traj_2709_7 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2709-dmpc-7.csv", DataFrame)
traj_2709_8 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2709-dmpc-8.csv", DataFrame)

traj_2710_1 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2710-dmpc-1.csv", DataFrame)
traj_2710_2 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2710-dmpc-2.csv", DataFrame)
traj_2710_3 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2710-dmpc-3.csv", DataFrame)
traj_2710_4 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2710-dmpc-4.csv", DataFrame)
traj_2710_5 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2710-dmpc-5.csv", DataFrame)
traj_2710_6 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2710-dmpc-6.csv", DataFrame)
traj_2710_7 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2710-dmpc-7.csv", DataFrame)
traj_2710_8 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2710-dmpc-8.csv", DataFrame)

traj_2711_1 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2711-dmpc-1.csv", DataFrame)
traj_2711_2 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2711-dmpc-2.csv", DataFrame)
traj_2711_3 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2711-dmpc-3.csv", DataFrame)
traj_2711_4 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2711-dmpc-4.csv", DataFrame)
traj_2711_5 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2711-dmpc-5.csv", DataFrame)
traj_2711_6 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2711-dmpc-6.csv", DataFrame)
traj_2711_7 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2711-dmpc-7.csv", DataFrame)
traj_2711_8 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2711-dmpc-8.csv", DataFrame)

traj_2712_1 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2712-dmpc-1.csv", DataFrame)
traj_2712_2 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2712-dmpc-2.csv", DataFrame)
traj_2712_3 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2712-dmpc-3.csv", DataFrame)
traj_2712_4 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2712-dmpc-4.csv", DataFrame)
traj_2712_5 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2712-dmpc-5.csv", DataFrame)
traj_2712_6 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2712-dmpc-6.csv", DataFrame)
traj_2712_7 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2712-dmpc-7.csv", DataFrame)
traj_2712_8 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2712-dmpc-8.csv", DataFrame)

traj_2713_1 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2713-dmpc-1.csv", DataFrame)
traj_2713_2 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2713-dmpc-2.csv", DataFrame)
traj_2713_3 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2713-dmpc-3.csv", DataFrame)
traj_2713_4 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2713-dmpc-4.csv", DataFrame)
traj_2713_5 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2713-dmpc-5.csv", DataFrame)
traj_2713_6 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2713-dmpc-6.csv", DataFrame)
traj_2713_7 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2713-dmpc-7.csv", DataFrame)
traj_2713_8 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2713-dmpc-8.csv", DataFrame)

traj_2714_1 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2714-dmpc-1.csv", DataFrame)
traj_2714_2 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2714-dmpc-2.csv", DataFrame)
traj_2714_3 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2714-dmpc-3.csv", DataFrame)
traj_2714_4 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2714-dmpc-4.csv", DataFrame)
traj_2714_5 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2714-dmpc-5.csv", DataFrame)
traj_2714_6 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2714-dmpc-6.csv", DataFrame)
traj_2714_7 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2714-dmpc-7.csv", DataFrame)
traj_2714_8 = CSV.read("C:\\Users\\ellio\\git\\gcn-dmpc\\final-analysis\\last-8-decompositions\\plot-instance\\traj-2714-dmpc-8.csv", DataFrame)

traj_1 = vcat(traj_2709_1, traj_2710_1, traj_2711_1, traj_2712_1, traj_2713_1, traj_2714_1)
traj_2 = vcat(traj_2709_2, traj_2710_2, traj_2711_2, traj_2712_2, traj_2713_2, traj_2714_2)
traj_3 = vcat(traj_2709_3, traj_2710_3, traj_2711_3, traj_2712_3, traj_2713_3, traj_2714_3)
traj_4 = vcat(traj_2709_4, traj_2710_4, traj_2711_4, traj_2712_4, traj_2713_4, traj_2714_4)
traj_5 = vcat(traj_2709_5, traj_2710_5, traj_2711_5, traj_2712_5, traj_2713_5, traj_2714_5)
traj_6 = vcat(traj_2709_6, traj_2710_6, traj_2711_6, traj_2712_6, traj_2713_6, traj_2714_6)
traj_7 = vcat(traj_2709_7, traj_2710_7, traj_2711_7, traj_2712_7, traj_2713_7, traj_2714_7)
traj_8 = vcat(traj_2709_8, traj_2710_8, traj_2711_8, traj_2712_8, traj_2713_8, traj_2714_8)

traj_class = vcat(traj_2709_1, traj_2710_5, traj_2711_8, traj_2712_7, traj_2713_7, traj_2714_8)
traj_best = vcat(traj_2709_1, traj_2710_5, traj_2711_2, traj_2712_7, traj_2713_8, traj_2714_8)

ns = [nrow(traj_2709_1), nrow(traj_2710_1), nrow(traj_2711_1), nrow(traj_2712_1), nrow(traj_2713_1), nrow(traj_2714_1)]
sp_T_1 = vcat(fill.(sp.T1_sp, ns)...)
sp_T_2 = vcat(fill.(sp.T2_sp, ns)...)
sp_T_3 = vcat(fill.(sp.T3_sp, ns)...)
sp_x_A1 = vcat(fill.(sp.xA1_sp, ns)...)
sp_x_B1 = vcat(fill.(sp.xB1_sp, ns)...)
sp_x_A2 = vcat(fill.(sp.xA2_sp, ns)...)
sp_x_B2 = vcat(fill.(sp.xB2_sp, ns)...)
sp_x_A3 = vcat(fill.(sp.xA3_sp, ns)...)
sp_x_B3 = vcat(fill.(sp.xB3_sp, ns)...)

sp_F_1 = vcat(fill.(sp.F1_sp, ns)...)
sp_F_2 = vcat(fill.(sp.F2_sp, ns)...)
sp_F_3 = vcat(fill.(sp.F3_sp, ns)...)
sp_F_f1 = vcat(fill.(sp.Ff1_sp, ns)...)
sp_F_f2 = vcat(fill.(sp.Ff2_sp, ns)...)
sp_F_R = vcat(fill.(sp.FR_sp, ns)...)
sp_Q_1 = vcat(fill.(sp.Q1_sp, ns)...)
sp_Q_2 = vcat(fill.(sp.Q2_sp, ns)...)
sp_Q_3 = vcat(fill.(sp.Q3_sp, ns)...)

plot(traj_4.T_1, label = false, lw = 3, c = c4)
plot!(traj_3.T_1, label = false, lw = 3, c = c3)
plot!(traj_2.T_1, label = false, lw = 3, c = c2)
plot!(traj_1.T_1, label = false, lw = 3, c = c1)
plot!(traj_5.T_1, label = false, lw = 3, c = c5)
plot!(traj_6.T_1, label = false, lw = 3, c = c6)
plot!(traj_7.T_1, label = false, lw = 3, c = c7)
plot!(traj_8.T_1, label = false, lw = 3, c = c8)
plot!(traj_class.T_1, label = false, lw = 3, c = :black, ls = :dot)
plot!([NaN], label = "DMPC 1", lw = 3, c = c1)
plot!([NaN], label = "DMPC 2", lw = 3, c = c2)
plot!([NaN], label = "DMPC 3", lw = 3, c = c3)
plot!([NaN], label = "DMPC 4", lw = 3, c = c4)
plot!([NaN], label = "DMPC 5", lw = 3, c = c5)
plot!([NaN], label = "DMPC 6", lw = 3, c = c6)
plot!([NaN], label = "DMPC 7", lw = 3, c = c7)
plot!([NaN], label = "DMPC 8", lw = 3, c = c8)
plot!(sp_T_1, label = "Set point", lw = 2, c = :gray, ls = :dot, dpi = 600, alpha = 0.6)
savefig("C:\\Users\\ellio\\git\\gcn-dmpc\\plots\\plotting-trajs\\traj-2709-2714-T1.png")

plot(traj_4.T_2, label = false, lw = 3, c = c4)
plot!(traj_3.T_2, label = false, lw = 3, c = c3)
plot!(traj_2.T_2, label = false, lw = 3, c = c2)
plot!(traj_1.T_2, label = false, lw = 3, c = c1)
plot!(traj_5.T_2, label = false, lw = 3, c = c5)
plot!(traj_6.T_2, label = false, lw = 3, c = c6)
plot!(traj_7.T_2, label = false, lw = 3, c = c7)
plot!(traj_8.T_2, label = false, lw = 3, c = c8)
plot!(traj_class.T_2, label = false, lw = 3, c = :black, ls = :dot)
plot!(sp_T_2, label = false, lw = 2, c = :gray, ls = :dot, dpi = 600, alpha = 0.6)
savefig("C:\\Users\\ellio\\git\\gcn-dmpc\\plots\\plotting-trajs\\traj-2709-2714-T2.png")

plot(traj_4.T_3, label = false, lw = 3, c = c4)
plot!(traj_3.T_3, label = false, lw = 3, c = c3)
plot!(traj_2.T_3, label = false, lw = 3, c = c2)
plot!(traj_1.T_3, label = false, lw = 3, c = c1)
plot!(traj_5.T_3, label = false, lw = 3, c = c5)
plot!(traj_6.T_3, label = false, lw = 3, c = c6)
plot!(traj_7.T_3, label = false, lw = 3, c = c7)
plot!(traj_8.T_3, label = false, lw = 3, c = c8)
plot!(traj_class.T_3, label = false, lw = 3, c = :black, ls = :dot)
plot!(sp_T_3, label = false, lw = 2, c = :gray, ls = :dot, dpi = 600, alpha = 0.6)
savefig("C:\\Users\\ellio\\git\\gcn-dmpc\\plots\\plotting-trajs\\traj-2709-2714-T3.png")

plot(traj_4.x_A1, label = false, lw = 3, c = c4)
plot!(traj_3.x_A1, label = false, lw = 3, c = c3)
plot!(traj_2.x_A1, label = false, lw = 3, c = c2)
plot!(traj_1.x_A1, label = false, lw = 3, c = c1)
plot!(traj_5.x_A1, label = false, lw = 3, c = c5)
plot!(traj_6.x_A1, label = false, lw = 3, c = c6)
plot!(traj_7.x_A1, label = false, lw = 3, c = c7)
plot!(traj_8.x_A1, label = false, lw = 3, c = c8)
plot!(traj_class.x_A1, label = false, lw = 3, c = :black, ls = :dot)
plot!(sp_x_A1, label = false, lw = 2, c = :gray, ls = :dot, dpi = 600, alpha = 0.6)
savefig("C:\\Users\\ellio\\git\\gcn-dmpc\\plots\\plotting-trajs\\traj-2709-2714-xA1.png")

plot(traj_4.x_A2, label = false, lw = 3, c = c4)
plot!(traj_3.x_A2, label = false, lw = 3, c = c3)
plot!(traj_2.x_A2, label = false, lw = 3, c = c2)
plot!(traj_1.x_A2, label = false, lw = 3, c = c1)
plot!(traj_5.x_A2, label = false, lw = 3, c = c5)
plot!(traj_6.x_A2, label = false, lw = 3, c = c6)
plot!(traj_7.x_A2, label = false, lw = 3, c = c7)
plot!(traj_8.x_A2, label = false, lw = 3, c = c8)
plot!(traj_class.x_A2, label = false, lw = 3, c = :black, ls = :dot)
plot!(sp_x_A2, label = false, lw = 2, c = :gray, ls = :dot, dpi = 600, alpha = 0.6)
savefig("C:\\Users\\ellio\\git\\gcn-dmpc\\plots\\plotting-trajs\\traj-2709-2714-xA2.png")

plot(traj_4.x_A3, label = false, lw = 3, c = c4)
plot!(traj_3.x_A3, label = false, lw = 3, c = c3)
plot!(traj_2.x_A3, label = false, lw = 3, c = c2)
plot!(traj_1.x_A3, label = false, lw = 3, c = c1)
plot!(traj_5.x_A3, label = false, lw = 3, c = c5)
plot!(traj_6.x_A3, label = false, lw = 3, c = c6)
plot!(traj_7.x_A3, label = false, lw = 3, c = c7)
plot!(traj_8.x_A3, label = false, lw = 3, c = c8)
plot!(traj_class.x_A3, label = false, lw = 3, c = :black, ls = :dot)
plot!(sp_x_A3, label = false, lw = 2, c = :gray, ls = :dot, dpi = 600, alpha = 0.6)
savefig("C:\\Users\\ellio\\git\\gcn-dmpc\\plots\\plotting-trajs\\traj-2709-2714-xA3.png")

plot(traj_4.x_B1, label = false, lw = 3, c = c4)
plot!(traj_3.x_B1, label = false, lw = 3, c = c3)
plot!(traj_2.x_B1, label = false, lw = 3, c = c2)
plot!(traj_1.x_B1, label = false, lw = 3, c = c1)
plot!(traj_5.x_B1, label = false, lw = 3, c = c5)
plot!(traj_6.x_B1, label = false, lw = 3, c = c6)
plot!(traj_7.x_B1, label = false, lw = 3, c = c7)
plot!(traj_8.x_B1, label = false, lw = 3, c = c8)
plot!(traj_class.x_B1, label = false, lw = 3, c = :black, ls = :dot)
plot!(sp_x_B1, label = false, lw = 2, c = :gray, ls = :dot, dpi = 600, alpha = 0.6)
savefig("C:\\Users\\ellio\\git\\gcn-dmpc\\plots\\plotting-trajs\\traj-2709-2714-xB1.png")

plot(traj_4.x_B2, label = false, lw = 3, c = c4)
plot!(traj_3.x_B2, label = false, lw = 3, c = c3)
plot!(traj_2.x_B2, label = false, lw = 3, c = c2)
plot!(traj_1.x_B2, label = false, lw = 3, c = c1)
plot!(traj_5.x_B2, label = false, lw = 3, c = c5)
plot!(traj_6.x_B2, label = false, lw = 3, c = c6)
plot!(traj_7.x_B2, label = false, lw = 3, c = c7)
plot!(traj_8.x_B2, label = false, lw = 3, c = c8)
plot!(traj_class.x_B2, label = false, lw = 3, c = :black, ls = :dot)
plot!(sp_x_B2, label = false, lw = 2, c = :gray, ls = :dot, dpi = 600, alpha = 0.6)
savefig("C:\\Users\\ellio\\git\\gcn-dmpc\\plots\\plotting-trajs\\traj-2709-2714-xB2.png")

plot(traj_4.x_B3, label = false, lw = 3, c = c4)
plot!(traj_3.x_B3, label = false, lw = 3, c = c3)
plot!(traj_2.x_B3, label = false, lw = 3, c = c2)
plot!(traj_1.x_B3, label = false, lw = 3, c = c1)
plot!(traj_5.x_B3, label = false, lw = 3, c = c5)
plot!(traj_6.x_B3, label = false, lw = 3, c = c6)
plot!(traj_7.x_B3, label = false, lw = 3, c = c7)
plot!(traj_8.x_B3, label = false, lw = 3, c = c8)
plot!(traj_class.x_B3, label = false, lw = 3, c = :black, ls = :dot)
plot!(sp_x_B3, label = false, lw = 2, c = :gray, ls = :dot, dpi = 600, alpha = 0.6)
savefig("C:\\Users\\ellio\\git\\gcn-dmpc\\plots\\plotting-trajs\\traj-2709-2714-xB3.png")

plot(traj_4.F_1, label = false, lw = 3, c = c4)
plot!(traj_3.F_1, label = false, lw = 3, c = c3)
plot!(traj_2.F_1, label = false, lw = 3, c = c2)
plot!(traj_1.F_1, label = false, lw = 3, c = c1)
plot!(traj_5.F_1, label = false, lw = 3, c = c5)
plot!(traj_6.F_1, label = false, lw = 3, c = c6)
plot!(traj_7.F_1, label = false, lw = 3, c = c7)
plot!(traj_8.F_1, label = false, lw = 3, c = c8)
plot!(traj_class.F_1, label = false, lw = 3, c = :black, ls = :dot)
plot!(sp_F_1, label = false, lw = 2, c = :gray, ls = :dot, dpi = 600, alpha = 0.6)
savefig("C:\\Users\\ellio\\git\\gcn-dmpc\\plots\\plotting-trajs\\traj-2709-2714-F1.png")

plot(traj_4.F_2, label = false, lw = 3, c = c4)
plot!(traj_3.F_2, label = false, lw = 3, c = c3)
plot!(traj_2.F_2, label = false, lw = 3, c = c2)
plot!(traj_1.F_2, label = false, lw = 3, c = c1)
plot!(traj_5.F_2, label = false, lw = 3, c = c5)
plot!(traj_6.F_2, label = false, lw = 3, c = c6)
plot!(traj_7.F_2, label = false, lw = 3, c = c7)
plot!(traj_8.F_2, label = false, lw = 3, c = c8)
plot!(traj_class.F_2, label = false, lw = 3, c = :black, ls = :dot)
plot!(sp_F_2, label = false, lw = 2, c = :gray, ls = :dot, dpi = 600, alpha = 0.6)
savefig("C:\\Users\\ellio\\git\\gcn-dmpc\\plots\\plotting-trajs\\traj-2709-2714-F2.png")

plot(traj_4.F_3, label = false, lw = 3, c = c4)
plot!(traj_3.F_3, label = false, lw = 3, c = c3)
plot!(traj_2.F_3, label = false, lw = 3, c = c2)
plot!(traj_1.F_3, label = false, lw = 3, c = c1)
plot!(traj_5.F_3, label = false, lw = 3, c = c5)
plot!(traj_6.F_3, label = false, lw = 3, c = c6)
plot!(traj_7.F_3, label = false, lw = 3, c = c7)
plot!(traj_8.F_3, label = false, lw = 3, c = c8)
plot!(traj_class.F_3, label = false, lw = 3, c = :black, ls = :dot)
plot!(sp_F_3, label = false, lw = 2, c = :gray, ls = :dot, dpi = 600, alpha = 0.6)
savefig("C:\\Users\\ellio\\git\\gcn-dmpc\\plots\\plotting-trajs\\traj-2709-2714-F3.png")

plot(traj_4.F_f1, label = false, lw = 3, c = c4)
plot!(traj_3.F_f1, label = false, lw = 3, c = c3)
plot!(traj_2.F_f1, label = false, lw = 3, c = c2)
plot!(traj_1.F_f1, label = false, lw = 3, c = c1)
plot!(traj_5.F_f1, label = false, lw = 3, c = c5)
plot!(traj_6.F_f1, label = false, lw = 3, c = c6)
plot!(traj_7.F_f1, label = false, lw = 3, c = c7)
plot!(traj_8.F_f1, label = false, lw = 3, c = c8)
plot!(traj_class.F_f1, label = false, lw = 3, c = :black, ls = :dot)
plot!(sp_F_f1, label = false, lw = 2, c = :gray, ls = :dot, dpi = 600, alpha = 0.6)
savefig("C:\\Users\\ellio\\git\\gcn-dmpc\\plots\\plotting-trajs\\traj-2709-2714-Ff1.png")

plot(traj_4.F_f2, label = false, lw = 3, c = c4)
plot!(traj_3.F_f2, label = false, lw = 3, c = c3)
plot!(traj_2.F_f2, label = false, lw = 3, c = c2)
plot!(traj_1.F_f2, label = false, lw = 3, c = c1)
plot!(traj_5.F_f2, label = false, lw = 3, c = c5)
plot!(traj_6.F_f2, label = false, lw = 3, c = c6)
plot!(traj_7.F_f2, label = false, lw = 3, c = c7)
plot!(traj_8.F_f2, label = false, lw = 3, c = c8)
plot!(traj_class.F_f2, label = false, lw = 3, c = :black, ls = :dot)
plot!(sp_F_f2, label = false, lw = 2, c = :gray, ls = :dot, dpi = 600, alpha = 0.6)
savefig("C:\\Users\\ellio\\git\\gcn-dmpc\\plots\\plotting-trajs\\traj-2709-2714-Ff2.png")

plot(traj_4.F_R, label = false, lw = 3, c = c4)
plot!(traj_3.F_R, label = false, lw = 3, c = c3)
plot!(traj_2.F_R, label = false, lw = 3, c = c2)
plot!(traj_1.F_R, label = false, lw = 3, c = c1)
plot!(traj_5.F_R, label = false, lw = 3, c = c5)
plot!(traj_6.F_R, label = false, lw = 3, c = c6)
plot!(traj_7.F_R, label = false, lw = 3, c = c7)
plot!(traj_8.F_R, label = false, lw = 3, c = c8)
plot!(traj_class.F_R, label = false, lw = 3, c = :black, ls = :dot)
plot!(sp_F_R, label = false, lw = 2, c = :gray, ls = :dot, dpi = 600, alpha = 0.6)
savefig("C:\\Users\\ellio\\git\\gcn-dmpc\\plots\\plotting-trajs\\traj-2709-2714-FR.png")

plot(traj_4.Q_1/100, label = false, lw = 3, c = c4)
plot!(traj_3.Q_1/100, label = false, lw = 3, c = c3)
plot!(traj_2.Q_1/100, label = false, lw = 3, c = c2)
plot!(traj_1.Q_1/100, label = false, lw = 3, c = c1)
plot!(traj_5.Q_1/100, label = false, lw = 3, c = c5)
plot!(traj_6.Q_1/100, label = false, lw = 3, c = c6)
plot!(traj_7.Q_1/100, label = false, lw = 3, c = c7)
plot!(traj_8.Q_1/100, label = false, lw = 3, c = c8)
plot!(traj_class.Q_1/100, label = false, lw = 3, c = :black, ls = :dot)
plot!(sp_Q_1/100, label = false, lw = 2, c = :gray, ls = :dot, dpi = 600, alpha = 0.6)
savefig("C:\\Users\\ellio\\git\\gcn-dmpc\\plots\\plotting-trajs\\traj-2709-2714-Q1.png")

plot(traj_4.Q_2, label = false, lw = 3, c = c4)
plot!(traj_3.Q_2, label = false, lw = 3, c = c3)
plot!(traj_2.Q_2, label = false, lw = 3, c = c2)
plot!(traj_1.Q_2, label = false, lw = 3, c = c1)
plot!(traj_5.Q_2, label = false, lw = 3, c = c5)
plot!(traj_6.Q_2, label = false, lw = 3, c = c6)
plot!(traj_7.Q_2, label = false, lw = 3, c = c7)
plot!(traj_8.Q_2, label = false, lw = 3, c = c8)
plot!(traj_class.Q_2, label = false, lw = 3, c = :black, ls = :dot)
plot!(sp_Q_2, label = false, lw = 2, c = :gray, ls = :dot, dpi = 600, alpha = 0.6)
savefig("C:\\Users\\ellio\\git\\gcn-dmpc\\plots\\plotting-trajs\\traj-2709-2714-Q2.png")

plot(traj_4.Q_3, label = false, lw = 3, c = c4)
plot!(traj_3.Q_3, label = false, lw = 3, c = c3)
plot!(traj_2.Q_3, label = false, lw = 3, c = c2)
plot!(traj_1.Q_3, label = false, lw = 3, c = c1)
plot!(traj_5.Q_3, label = false, lw = 3, c = c5)
plot!(traj_6.Q_3, label = false, lw = 3, c = c6)
plot!(traj_7.Q_3, label = false, lw = 3, c = c7)
plot!(traj_8.Q_3, label = false, lw = 3, c = c8)
plot!(traj_class.Q_3, label = false, lw = 3, c = :black, ls = :dot)
plot!(sp_Q_3, label = false, lw = 2, c = :gray, ls = :dot, dpi = 600, alpha = 0.6)
savefig("C:\\Users\\ellio\\git\\gcn-dmpc\\plots\\plotting-trajs\\traj-2709-2714-Q3.png")